name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  sign_in_with_apple: ^6.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  numberpicker: ^2.1.2
  flutter_ruler_picker: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.2.1
  dotted_border: ^2.1.0
  dotted_line: ^3.1.0
  icons_plus: ^5.0.0
  cloud_firestore: ^5.6.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/google.png
     - images/Adidas.png
     - images/apple.png
     - images/cactus.png
     - images/change_password.png
     - images/new_password.png
     - images/sent_successfully.png
     - images/empty_notification.png
     - images/favourite_empty.png
     - images/booking_empty.png
     - images/cart_empty.png
     - images/confirmation.png
     - images/king.png
     - images/home.png
     - images/seif.jpg
     - images/Tshirt.png
     - images/fila-9 1.png
     - images/human.png
     - images/product.png
     - icons/qlementine-icons_password-16.svg
     - icons/Bag.svg
     - icons/fluent_person-28-regular.svg
     - icons/hugeicons_home-05.svg
     - icons/search.svg
     - icons/solar_heart-outline.svg
     - icons/Subtract.svg
     - icons/delete.svg
     - icons/policy.svg
     - icons/email.svg
     - icons/confirm_password.svg
     - icons/exclamation (16) 1.svg
     - icons/skip.svg
     - icons/new_passowrd.svg
     - icons/solar_user-outline.svg
     - icons/success-IXzuHjaasy.svg
     - icons/hugeicons_edit-02.svg
     - icons/trash.svg
     - icons/bell.svg
     - icons/search.svg
     - icons/menu.svg
     - icons/streamline-ultimate_reward-stars-4-bold.svg
     - icons/bxs_hot.svg
     - icons/bxs_offer.svg
     - icons/Nav bar.svg
     - icons/solar_user-outline.svg
     - icons/material-symbols-light_history-edu-outline-rounded.svg
     - icons/fluent_wallet-credit-card-28-regular.svg
     - icons/material-symbols-light_language.svg
     - icons/terms.svg
     - icons/solar_shop-outline.svg
     - icons/fa6-solid_person.svg
     - images/avatar.png
     - icons/triangle.svg
     - icons/edit.svg
     - icons/phone.svg
     - icons/search_Button.svg
     - icons/Frame 30.svg
     - icons/nav_search.svg
     - icons/height_triangle.svg

  fonts:
    - family: kreon
      fonts:
        - asset: fonts/Kreon-Regular.ttf
        - asset: fonts/Kreon-Medium.ttf
          weight: 500
        - asset: fonts/Kreon-SemiBold.ttf
          weight: 600
        - asset: fonts/Kreon-Bold.ttf
          weight: 700   
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
